name:  Deploy

on:
  pull_request:
    branches: [ develop, staging, main ]

jobs:
  deploy-develop:
    name: Deploy to develop
    if: github.event.ref === 'refs/heads/develop' && github.event_name == 'pull_request'
    environment:
      name: Develop
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Fake Dev Deploy
        run: echo "Deploying to Dev"
